from personalized_nlp.transfer_learning_methods.base import train_test_base_model
from personalized_nlp.transfer_learning_methods.random_numbers import train_test_random_transfer
from personalized_nlp.transfer_learning_methods.transfer_learning import train_test_transfer_learning
